import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs";

const SLIDES_API_URL = process.env.SLIDES_API_URL || "http://localhost:8000";

interface ExportPdfRequest {
  id: string;
  title?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: ExportPdfRequest = await request.json();
    const { id, title } = body;

    if (!id) {
      return NextResponse.json({ error: "Missing id parameter" }, { status: 400 });
    }

    // For now, we'll redirect to PPTX export as PDF export requires Puppeteer/browser rendering
    // In a full implementation, this would:
    // 1. Render each slide to HTML
    // 2. Use Puppeteer to generate PDF from HTML
    // 3. Merge PDFs into a single file

    // For now, return a message that PDF export is not yet implemented
    // and the user should use PPTX export
    console.log(`PDF export requested for presentation ${id} with title "${title}"`);

    // Create a placeholder response - in production this would generate a real PDF
    const exportDir = path.join(process.cwd(), "app_data", "exports");

    // Ensure directory exists
    if (!fs.existsSync(exportDir)) {
      fs.mkdirSync(exportDir, { recursive: true });
    }

    // For now, return the PPTX path format
    // (the actual file would be generated by the backend)
    const sanitizedTitle = (title || id).replace(/[^a-zA-Z0-9-_]/g, "_");
    const pdfPath = `/api/slides/v1/static/exports/${sanitizedTitle}.pdf`;

    // Note: In a real implementation, we would generate the PDF here
    // For now, we'll return a response that indicates the path
    // The FastAPI backend will handle the actual file serving

    return NextResponse.json({
      path: pdfPath,
      message: "PDF export path generated",
    });
  } catch (error) {
    console.error("Error in /api/export-as-pdf:", error);
    return NextResponse.json(
      {
        error: "Failed to export as PDF",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
